package net.megx.megdb.services;

import net.megx.megdb.beans.Articles;
import net.megx.megdb.beans.ArticlesExample;
import org.apache.ibatis.annotations.Param;

public interface ArticlesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int countByExample(ArticlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int deleteByPrimaryKey(@Param("id") String id,
			@Param("idCode") String idCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int insert(Articles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int insertSelective(Articles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	Articles selectByPrimaryKey(@Param("id") String id,
			@Param("idCode") String idCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int updateByExampleSelective(@Param("record") Articles record,
			@Param("example") ArticlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int updateByExample(@Param("record") Articles record,
			@Param("example") ArticlesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int updateByPrimaryKeySelective(Articles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	int updateByPrimaryKey(Articles record);
}