package net.megx.megdb.beans;

public class Articles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.id
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.id_code
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String idCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.title
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.pubstatus
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String pubstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.linkout
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private Object linkout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.journalid
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private Integer journalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.issue
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String issue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.volume
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String volume;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.yr
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String yr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.mon
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String mon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.firstpage
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String firstpage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.lastpage
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String lastpage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.abstract
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private String articleAbstract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.published
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private Boolean published;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.pdf
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private Object pdf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.html_abstract
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private Object htmlAbstract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.articles.html_fulltext
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	private Object htmlFulltext;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.id
	 * @return  the value of core.articles.id
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.id
	 * @param id  the value for core.articles.id
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.id_code
	 * @return  the value of core.articles.id_code
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getIdCode() {
		return idCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.id_code
	 * @param idCode  the value for core.articles.id_code
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setIdCode(String idCode) {
		this.idCode = idCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.title
	 * @return  the value of core.articles.title
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.title
	 * @param title  the value for core.articles.title
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.pubstatus
	 * @return  the value of core.articles.pubstatus
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getPubstatus() {
		return pubstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.pubstatus
	 * @param pubstatus  the value for core.articles.pubstatus
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setPubstatus(String pubstatus) {
		this.pubstatus = pubstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.linkout
	 * @return  the value of core.articles.linkout
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public Object getLinkout() {
		return linkout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.linkout
	 * @param linkout  the value for core.articles.linkout
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setLinkout(Object linkout) {
		this.linkout = linkout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.journalid
	 * @return  the value of core.articles.journalid
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public Integer getJournalid() {
		return journalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.journalid
	 * @param journalid  the value for core.articles.journalid
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setJournalid(Integer journalid) {
		this.journalid = journalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.issue
	 * @return  the value of core.articles.issue
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getIssue() {
		return issue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.issue
	 * @param issue  the value for core.articles.issue
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setIssue(String issue) {
		this.issue = issue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.volume
	 * @return  the value of core.articles.volume
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getVolume() {
		return volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.volume
	 * @param volume  the value for core.articles.volume
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setVolume(String volume) {
		this.volume = volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.yr
	 * @return  the value of core.articles.yr
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getYr() {
		return yr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.yr
	 * @param yr  the value for core.articles.yr
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setYr(String yr) {
		this.yr = yr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.mon
	 * @return  the value of core.articles.mon
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getMon() {
		return mon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.mon
	 * @param mon  the value for core.articles.mon
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setMon(String mon) {
		this.mon = mon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.firstpage
	 * @return  the value of core.articles.firstpage
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getFirstpage() {
		return firstpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.firstpage
	 * @param firstpage  the value for core.articles.firstpage
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setFirstpage(String firstpage) {
		this.firstpage = firstpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.lastpage
	 * @return  the value of core.articles.lastpage
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getLastpage() {
		return lastpage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.lastpage
	 * @param lastpage  the value for core.articles.lastpage
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setLastpage(String lastpage) {
		this.lastpage = lastpage; 
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.abstract
	 * @return  the value of core.articles.abstract
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public String getArticleAbstract() {
		return articleAbstract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.abstract
	 * @param articleAbstract  the value for core.articles.abstract
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setArticleAbstract(String articleAbstract) {
		this.articleAbstract = articleAbstract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.published
	 * @return  the value of core.articles.published
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public Boolean getPublished() {
		return published;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.published
	 * @param published  the value for core.articles.published
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setPublished(Boolean published) {
		this.published = published;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.pdf
	 * @return  the value of core.articles.pdf
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public Object getPdf() {
		return pdf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.pdf
	 * @param pdf  the value for core.articles.pdf
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setPdf(Object pdf) {
		this.pdf = pdf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.html_abstract
	 * @return  the value of core.articles.html_abstract
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public Object getHtmlAbstract() {
		return htmlAbstract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.html_abstract
	 * @param htmlAbstract  the value for core.articles.html_abstract
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setHtmlAbstract(Object htmlAbstract) {
		this.htmlAbstract = htmlAbstract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.articles.html_fulltext
	 * @return  the value of core.articles.html_fulltext
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public Object getHtmlFulltext() {
		return htmlFulltext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.articles.html_fulltext
	 * @param htmlFulltext  the value for core.articles.html_fulltext
	 * @mbggenerated  Wed Jun 13 06:05:50 CEST 2012
	 */
	public void setHtmlFulltext(Object htmlFulltext) {
		this.htmlFulltext = htmlFulltext;
	}

   

    
}