package net.megx.megdb.beans;

import java.util.ArrayList;
import java.util.List;

public class ArticlesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public ArticlesExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("Article.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("Article.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("Article.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("Article.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("Article.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("Article.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("Article.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("Article.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("Article.id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("Article.id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("Article.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("Article.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("Article.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("Article.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdCodeIsNull() {
			addCriterion("Article.id_code is null");
			return (Criteria) this;
		}

		public Criteria andIdCodeIsNotNull() {
			addCriterion("Article.id_code is not null");
			return (Criteria) this;
		}

		public Criteria andIdCodeEqualTo(String value) {
			addCriterion("Article.id_code =", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeNotEqualTo(String value) {
			addCriterion("Article.id_code <>", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeGreaterThan(String value) {
			addCriterion("Article.id_code >", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeGreaterThanOrEqualTo(String value) {
			addCriterion("Article.id_code >=", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeLessThan(String value) {
			addCriterion("Article.id_code <", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeLessThanOrEqualTo(String value) {
			addCriterion("Article.id_code <=", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeLike(String value) {
			addCriterion("Article.id_code like", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeNotLike(String value) {
			addCriterion("Article.id_code not like", value, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeIn(List<String> values) {
			addCriterion("Article.id_code in", values, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeNotIn(List<String> values) {
			addCriterion("Article.id_code not in", values, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeBetween(String value1, String value2) {
			addCriterion("Article.id_code between", value1, value2, "idCode");
			return (Criteria) this;
		}

		public Criteria andIdCodeNotBetween(String value1, String value2) {
			addCriterion("Article.id_code not between", value1, value2,
					"idCode");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("Article.title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("Article.title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("Article.title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("Article.title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("Article.title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("Article.title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("Article.title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("Article.title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("Article.title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("Article.title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("Article.title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("Article.title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("Article.title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("Article.title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andPubstatusIsNull() {
			addCriterion("Article.pubstatus is null");
			return (Criteria) this;
		}

		public Criteria andPubstatusIsNotNull() {
			addCriterion("Article.pubstatus is not null");
			return (Criteria) this;
		}

		public Criteria andPubstatusEqualTo(String value) {
			addCriterion("Article.pubstatus =", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusNotEqualTo(String value) {
			addCriterion("Article.pubstatus <>", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusGreaterThan(String value) {
			addCriterion("Article.pubstatus >", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusGreaterThanOrEqualTo(String value) {
			addCriterion("Article.pubstatus >=", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusLessThan(String value) {
			addCriterion("Article.pubstatus <", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusLessThanOrEqualTo(String value) {
			addCriterion("Article.pubstatus <=", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusLike(String value) {
			addCriterion("Article.pubstatus like", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusNotLike(String value) {
			addCriterion("Article.pubstatus not like", value, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusIn(List<String> values) {
			addCriterion("Article.pubstatus in", values, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusNotIn(List<String> values) {
			addCriterion("Article.pubstatus not in", values, "pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusBetween(String value1, String value2) {
			addCriterion("Article.pubstatus between", value1, value2,
					"pubstatus");
			return (Criteria) this;
		}

		public Criteria andPubstatusNotBetween(String value1, String value2) {
			addCriterion("Article.pubstatus not between", value1, value2,
					"pubstatus");
			return (Criteria) this;
		}

		public Criteria andLinkoutIsNull() {
			addCriterion("Article.linkout is null");
			return (Criteria) this;
		}

		public Criteria andLinkoutIsNotNull() {
			addCriterion("Article.linkout is not null");
			return (Criteria) this;
		}

		public Criteria andLinkoutEqualTo(Object value) {
			addCriterion("Article.linkout =", value, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutNotEqualTo(Object value) {
			addCriterion("Article.linkout <>", value, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutGreaterThan(Object value) {
			addCriterion("Article.linkout >", value, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutGreaterThanOrEqualTo(Object value) {
			addCriterion("Article.linkout >=", value, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutLessThan(Object value) {
			addCriterion("Article.linkout <", value, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutLessThanOrEqualTo(Object value) {
			addCriterion("Article.linkout <=", value, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutIn(List<Object> values) {
			addCriterion("Article.linkout in", values, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutNotIn(List<Object> values) {
			addCriterion("Article.linkout not in", values, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutBetween(Object value1, Object value2) {
			addCriterion("Article.linkout between", value1, value2, "linkout");
			return (Criteria) this;
		}

		public Criteria andLinkoutNotBetween(Object value1, Object value2) {
			addCriterion("Article.linkout not between", value1, value2,
					"linkout");
			return (Criteria) this;
		}

		public Criteria andJournalidIsNull() {
			addCriterion("Article.journalid is null");
			return (Criteria) this;
		}

		public Criteria andJournalidIsNotNull() {
			addCriterion("Article.journalid is not null");
			return (Criteria) this;
		}

		public Criteria andJournalidEqualTo(Integer value) {
			addCriterion("Article.journalid =", value, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidNotEqualTo(Integer value) {
			addCriterion("Article.journalid <>", value, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidGreaterThan(Integer value) {
			addCriterion("Article.journalid >", value, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidGreaterThanOrEqualTo(Integer value) {
			addCriterion("Article.journalid >=", value, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidLessThan(Integer value) {
			addCriterion("Article.journalid <", value, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidLessThanOrEqualTo(Integer value) {
			addCriterion("Article.journalid <=", value, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidIn(List<Integer> values) {
			addCriterion("Article.journalid in", values, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidNotIn(List<Integer> values) {
			addCriterion("Article.journalid not in", values, "journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidBetween(Integer value1, Integer value2) {
			addCriterion("Article.journalid between", value1, value2,
					"journalid");
			return (Criteria) this;
		}

		public Criteria andJournalidNotBetween(Integer value1, Integer value2) {
			addCriterion("Article.journalid not between", value1, value2,
					"journalid");
			return (Criteria) this;
		}

		public Criteria andIssueIsNull() {
			addCriterion("Article.issue is null");
			return (Criteria) this;
		}

		public Criteria andIssueIsNotNull() {
			addCriterion("Article.issue is not null");
			return (Criteria) this;
		}

		public Criteria andIssueEqualTo(String value) {
			addCriterion("Article.issue =", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueNotEqualTo(String value) {
			addCriterion("Article.issue <>", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueGreaterThan(String value) {
			addCriterion("Article.issue >", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueGreaterThanOrEqualTo(String value) {
			addCriterion("Article.issue >=", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueLessThan(String value) {
			addCriterion("Article.issue <", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueLessThanOrEqualTo(String value) {
			addCriterion("Article.issue <=", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueLike(String value) {
			addCriterion("Article.issue like", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueNotLike(String value) {
			addCriterion("Article.issue not like", value, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueIn(List<String> values) {
			addCriterion("Article.issue in", values, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueNotIn(List<String> values) {
			addCriterion("Article.issue not in", values, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueBetween(String value1, String value2) {
			addCriterion("Article.issue between", value1, value2, "issue");
			return (Criteria) this;
		}

		public Criteria andIssueNotBetween(String value1, String value2) {
			addCriterion("Article.issue not between", value1, value2, "issue");
			return (Criteria) this;
		}

		public Criteria andVolumeIsNull() {
			addCriterion("Article.volume is null");
			return (Criteria) this;
		}

		public Criteria andVolumeIsNotNull() {
			addCriterion("Article.volume is not null");
			return (Criteria) this;
		}

		public Criteria andVolumeEqualTo(String value) {
			addCriterion("Article.volume =", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotEqualTo(String value) {
			addCriterion("Article.volume <>", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeGreaterThan(String value) {
			addCriterion("Article.volume >", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeGreaterThanOrEqualTo(String value) {
			addCriterion("Article.volume >=", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeLessThan(String value) {
			addCriterion("Article.volume <", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeLessThanOrEqualTo(String value) {
			addCriterion("Article.volume <=", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeLike(String value) {
			addCriterion("Article.volume like", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotLike(String value) {
			addCriterion("Article.volume not like", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeIn(List<String> values) {
			addCriterion("Article.volume in", values, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotIn(List<String> values) {
			addCriterion("Article.volume not in", values, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeBetween(String value1, String value2) {
			addCriterion("Article.volume between", value1, value2, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotBetween(String value1, String value2) {
			addCriterion("Article.volume not between", value1, value2, "volume");
			return (Criteria) this;
		}

		public Criteria andYrIsNull() {
			addCriterion("Article.yr is null");
			return (Criteria) this;
		}

		public Criteria andYrIsNotNull() {
			addCriterion("Article.yr is not null");
			return (Criteria) this;
		}

		public Criteria andYrEqualTo(String value) {
			addCriterion("Article.yr =", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrNotEqualTo(String value) {
			addCriterion("Article.yr <>", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrGreaterThan(String value) {
			addCriterion("Article.yr >", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrGreaterThanOrEqualTo(String value) {
			addCriterion("Article.yr >=", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrLessThan(String value) {
			addCriterion("Article.yr <", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrLessThanOrEqualTo(String value) {
			addCriterion("Article.yr <=", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrLike(String value) {
			addCriterion("Article.yr like", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrNotLike(String value) {
			addCriterion("Article.yr not like", value, "yr");
			return (Criteria) this;
		}

		public Criteria andYrIn(List<String> values) {
			addCriterion("Article.yr in", values, "yr");
			return (Criteria) this;
		}

		public Criteria andYrNotIn(List<String> values) {
			addCriterion("Article.yr not in", values, "yr");
			return (Criteria) this;
		}

		public Criteria andYrBetween(String value1, String value2) {
			addCriterion("Article.yr between", value1, value2, "yr");
			return (Criteria) this;
		}

		public Criteria andYrNotBetween(String value1, String value2) {
			addCriterion("Article.yr not between", value1, value2, "yr");
			return (Criteria) this;
		}

		public Criteria andMonIsNull() {
			addCriterion("Article.mon is null");
			return (Criteria) this;
		}

		public Criteria andMonIsNotNull() {
			addCriterion("Article.mon is not null");
			return (Criteria) this;
		}

		public Criteria andMonEqualTo(String value) {
			addCriterion("Article.mon =", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonNotEqualTo(String value) {
			addCriterion("Article.mon <>", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonGreaterThan(String value) {
			addCriterion("Article.mon >", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonGreaterThanOrEqualTo(String value) {
			addCriterion("Article.mon >=", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonLessThan(String value) {
			addCriterion("Article.mon <", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonLessThanOrEqualTo(String value) {
			addCriterion("Article.mon <=", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonLike(String value) {
			addCriterion("Article.mon like", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonNotLike(String value) {
			addCriterion("Article.mon not like", value, "mon");
			return (Criteria) this;
		}

		public Criteria andMonIn(List<String> values) {
			addCriterion("Article.mon in", values, "mon");
			return (Criteria) this;
		}

		public Criteria andMonNotIn(List<String> values) {
			addCriterion("Article.mon not in", values, "mon");
			return (Criteria) this;
		}

		public Criteria andMonBetween(String value1, String value2) {
			addCriterion("Article.mon between", value1, value2, "mon");
			return (Criteria) this;
		}

		public Criteria andMonNotBetween(String value1, String value2) {
			addCriterion("Article.mon not between", value1, value2, "mon");
			return (Criteria) this;
		}

		public Criteria andFirstpageIsNull() {
			addCriterion("Article.firstpage is null");
			return (Criteria) this;
		}

		public Criteria andFirstpageIsNotNull() {
			addCriterion("Article.firstpage is not null");
			return (Criteria) this;
		}

		public Criteria andFirstpageEqualTo(String value) {
			addCriterion("Article.firstpage =", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageNotEqualTo(String value) {
			addCriterion("Article.firstpage <>", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageGreaterThan(String value) {
			addCriterion("Article.firstpage >", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageGreaterThanOrEqualTo(String value) {
			addCriterion("Article.firstpage >=", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageLessThan(String value) {
			addCriterion("Article.firstpage <", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageLessThanOrEqualTo(String value) {
			addCriterion("Article.firstpage <=", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageLike(String value) {
			addCriterion("Article.firstpage like", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageNotLike(String value) {
			addCriterion("Article.firstpage not like", value, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageIn(List<String> values) {
			addCriterion("Article.firstpage in", values, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageNotIn(List<String> values) {
			addCriterion("Article.firstpage not in", values, "firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageBetween(String value1, String value2) {
			addCriterion("Article.firstpage between", value1, value2,
					"firstpage");
			return (Criteria) this;
		}

		public Criteria andFirstpageNotBetween(String value1, String value2) {
			addCriterion("Article.firstpage not between", value1, value2,
					"firstpage");
			return (Criteria) this;
		}

		public Criteria andLastpageIsNull() {
			addCriterion("Article.lastpage is null");
			return (Criteria) this;
		}

		public Criteria andLastpageIsNotNull() {
			addCriterion("Article.lastpage is not null");
			return (Criteria) this;
		}

		public Criteria andLastpageEqualTo(String value) {
			addCriterion("Article.lastpage =", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageNotEqualTo(String value) {
			addCriterion("Article.lastpage <>", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageGreaterThan(String value) {
			addCriterion("Article.lastpage >", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageGreaterThanOrEqualTo(String value) {
			addCriterion("Article.lastpage >=", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageLessThan(String value) {
			addCriterion("Article.lastpage <", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageLessThanOrEqualTo(String value) {
			addCriterion("Article.lastpage <=", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageLike(String value) {
			addCriterion("Article.lastpage like", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageNotLike(String value) {
			addCriterion("Article.lastpage not like", value, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageIn(List<String> values) {
			addCriterion("Article.lastpage in", values, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageNotIn(List<String> values) {
			addCriterion("Article.lastpage not in", values, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageBetween(String value1, String value2) {
			addCriterion("Article.lastpage between", value1, value2, "lastpage");
			return (Criteria) this;
		}

		public Criteria andLastpageNotBetween(String value1, String value2) {
			addCriterion("Article.lastpage not between", value1, value2,
					"lastpage");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractIsNull() {
			addCriterion("Article.abstract is null");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractIsNotNull() {
			addCriterion("Article.abstract is not null");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractEqualTo(String value) {
			addCriterion("Article.abstract =", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractNotEqualTo(String value) {
			addCriterion("Article.abstract <>", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractGreaterThan(String value) {
			addCriterion("Article.abstract >", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractGreaterThanOrEqualTo(String value) {
			addCriterion("Article.abstract >=", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractLessThan(String value) {
			addCriterion("Article.abstract <", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractLessThanOrEqualTo(String value) {
			addCriterion("Article.abstract <=", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractLike(String value) {
			addCriterion("Article.abstract like", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractNotLike(String value) {
			addCriterion("Article.abstract not like", value, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractIn(List<String> values) {
			addCriterion("Article.abstract in", values, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractNotIn(List<String> values) {
			addCriterion("Article.abstract not in", values, "articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractBetween(String value1, String value2) {
			addCriterion("Article.abstract between", value1, value2,
					"articleAbstract");
			return (Criteria) this;
		}

		public Criteria andArticleAbstractNotBetween(String value1,
				String value2) {
			addCriterion("Article.abstract not between", value1, value2,
					"articleAbstract");
			return (Criteria) this;
		}

		public Criteria andPublishedIsNull() {
			addCriterion("Article.published is null");
			return (Criteria) this;
		}

		public Criteria andPublishedIsNotNull() {
			addCriterion("Article.published is not null");
			return (Criteria) this;
		}

		public Criteria andPublishedEqualTo(Boolean value) {
			addCriterion("Article.published =", value, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedNotEqualTo(Boolean value) {
			addCriterion("Article.published <>", value, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedGreaterThan(Boolean value) {
			addCriterion("Article.published >", value, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("Article.published >=", value, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedLessThan(Boolean value) {
			addCriterion("Article.published <", value, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedLessThanOrEqualTo(Boolean value) {
			addCriterion("Article.published <=", value, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedIn(List<Boolean> values) {
			addCriterion("Article.published in", values, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedNotIn(List<Boolean> values) {
			addCriterion("Article.published not in", values, "published");
			return (Criteria) this;
		}

		public Criteria andPublishedBetween(Boolean value1, Boolean value2) {
			addCriterion("Article.published between", value1, value2,
					"published");
			return (Criteria) this;
		}

		public Criteria andPublishedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("Article.published not between", value1, value2,
					"published");
			return (Criteria) this;
		}

		public Criteria andPdfIsNull() {
			addCriterion("Article.pdf is null");
			return (Criteria) this;
		}

		public Criteria andPdfIsNotNull() {
			addCriterion("Article.pdf is not null");
			return (Criteria) this;
		}

		public Criteria andPdfEqualTo(Object value) {
			addCriterion("Article.pdf =", value, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfNotEqualTo(Object value) {
			addCriterion("Article.pdf <>", value, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfGreaterThan(Object value) {
			addCriterion("Article.pdf >", value, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfGreaterThanOrEqualTo(Object value) {
			addCriterion("Article.pdf >=", value, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfLessThan(Object value) {
			addCriterion("Article.pdf <", value, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfLessThanOrEqualTo(Object value) {
			addCriterion("Article.pdf <=", value, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfIn(List<Object> values) {
			addCriterion("Article.pdf in", values, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfNotIn(List<Object> values) {
			addCriterion("Article.pdf not in", values, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfBetween(Object value1, Object value2) {
			addCriterion("Article.pdf between", value1, value2, "pdf");
			return (Criteria) this;
		}

		public Criteria andPdfNotBetween(Object value1, Object value2) {
			addCriterion("Article.pdf not between", value1, value2, "pdf");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractIsNull() {
			addCriterion("Article.html_abstract is null");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractIsNotNull() {
			addCriterion("Article.html_abstract is not null");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractEqualTo(Object value) {
			addCriterion("Article.html_abstract =", value, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractNotEqualTo(Object value) {
			addCriterion("Article.html_abstract <>", value, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractGreaterThan(Object value) {
			addCriterion("Article.html_abstract >", value, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractGreaterThanOrEqualTo(Object value) {
			addCriterion("Article.html_abstract >=", value, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractLessThan(Object value) {
			addCriterion("Article.html_abstract <", value, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractLessThanOrEqualTo(Object value) {
			addCriterion("Article.html_abstract <=", value, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractIn(List<Object> values) {
			addCriterion("Article.html_abstract in", values, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractNotIn(List<Object> values) {
			addCriterion("Article.html_abstract not in", values, "htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractBetween(Object value1, Object value2) {
			addCriterion("Article.html_abstract between", value1, value2,
					"htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlAbstractNotBetween(Object value1, Object value2) {
			addCriterion("Article.html_abstract not between", value1, value2,
					"htmlAbstract");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextIsNull() {
			addCriterion("Article.html_fulltext is null");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextIsNotNull() {
			addCriterion("Article.html_fulltext is not null");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextEqualTo(Object value) {
			addCriterion("Article.html_fulltext =", value, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextNotEqualTo(Object value) {
			addCriterion("Article.html_fulltext <>", value, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextGreaterThan(Object value) {
			addCriterion("Article.html_fulltext >", value, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextGreaterThanOrEqualTo(Object value) {
			addCriterion("Article.html_fulltext >=", value, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextLessThan(Object value) {
			addCriterion("Article.html_fulltext <", value, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextLessThanOrEqualTo(Object value) {
			addCriterion("Article.html_fulltext <=", value, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextIn(List<Object> values) {
			addCriterion("Article.html_fulltext in", values, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextNotIn(List<Object> values) {
			addCriterion("Article.html_fulltext not in", values, "htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextBetween(Object value1, Object value2) {
			addCriterion("Article.html_fulltext between", value1, value2,
					"htmlFulltext");
			return (Criteria) this;
		}

		public Criteria andHtmlFulltextNotBetween(Object value1, Object value2) {
			addCriterion("Article.html_fulltext not between", value1, value2,
					"htmlFulltext");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.articles
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.articles
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 13 05:34:00 CEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}