package net.megx.model;

public interface Author {

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.authors.first_name
	 * @return  the value of core.authors.first_name
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public String getFirstName();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.authors.first_name
	 * @param firstName  the value for core.authors.first_name
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public void setFirstName(String firstName);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.authors.last_name
	 * @return  the value of core.authors.last_name
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public String getLastName();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.authors.last_name
	 * @param lastName  the value for core.authors.last_name
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public void setLastName(String lastName);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.authors.initials
	 * @return  the value of core.authors.initials
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public String getInitials();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.authors.initials
	 * @param initials  the value for core.authors.initials
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public void setInitials(String initials);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.authors.sex
	 * @return  the value of core.authors.sex
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public String getSex();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.authors.sex
	 * @param sex  the value for core.authors.sex
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public void setSex(String sex);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.authors.institute
	 * @return  the value of core.authors.institute
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public String getInstitute();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.authors.institute
	 * @param institute  the value for core.authors.institute
	 * @mbggenerated  Wed Jun 13 17:13:52 CEST 2012
	 */
	public void setInstitute(String institute);

}