package net.megx.model;

import java.util.Date;

public interface Journal {

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.title
	 * @return  the value of core.journals.title
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getTitle();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.title
	 * @param title  the value for core.journals.title
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setTitle(String title);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.publisher
	 * @return  the value of core.journals.publisher
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getPublisher();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.publisher
	 * @param publisher  the value for core.journals.publisher
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setPublisher(String publisher);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.iso_abbr
	 * @return  the value of core.journals.iso_abbr
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getIsoAbbr();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.iso_abbr
	 * @param isoAbbr  the value for core.journals.iso_abbr
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setIsoAbbr(String isoAbbr);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.med_abbr
	 * @return  the value of core.journals.med_abbr
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getMedAbbr();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.med_abbr
	 * @param medAbbr  the value for core.journals.med_abbr
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setMedAbbr(String medAbbr);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.homepage
	 * @return  the value of core.journals.homepage
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getHomepage();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.homepage
	 * @param homepage  the value for core.journals.homepage
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setHomepage(String homepage);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.pissn
	 * @return  the value of core.journals.pissn
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getPissn();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.pissn
	 * @param pissn  the value for core.journals.pissn
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setPissn(String pissn);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.eissn
	 * @return  the value of core.journals.eissn
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getEissn();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.eissn
	 * @param eissn  the value for core.journals.eissn
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setEissn(String eissn);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.country
	 * @return  the value of core.journals.country
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getCountry();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.country
	 * @param country  the value for core.journals.country
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setCountry(String country);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.pubstart
	 * @return  the value of core.journals.pubstart
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getPubstart();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.pubstart
	 * @param pubstart  the value for core.journals.pubstart
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setPubstart(String pubstart);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.lang
	 * @return  the value of core.journals.lang
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getLang();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.lang
	 * @param lang  the value for core.journals.lang
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setLang(String lang);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.nlmid
	 * @return  the value of core.journals.nlmid
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public String getNlmid();

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.journals.nlmid
	 * @param nlmid  the value for core.journals.nlmid
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public void setNlmid(String nlmid);

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.created
	 * @return  the value of core.journals.created
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public Date getCreated();

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.journals.updated
	 * @return  the value of core.journals.updated
	 * @mbggenerated  Wed Jun 13 17:04:37 CEST 2012
	 */
	public Date getUpdated();

}