package net.megx.model;

import java.math.BigDecimal;
import java.util.Date;

public interface Sample {

	public String getStudy();

	public void setStudy(String study);

	public String getLabel();

	public void setLabel(String label);

	public BigDecimal getMaxUncertain();

	public void setMaxUncertain(BigDecimal maxUncertain);

	public Date getDateTaken();

	public void setDateTaken(Date dateTaken);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.date_res
	 *
	 * @return the value of core.samples.date_res
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getDateRes();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.date_res
	 *
	 * @param dateRes the value for core.samples.date_res
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setDateRes(String dateRes);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.material
	 *
	 * @return the value of core.samples.material
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getMaterial();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.material
	 *
	 * @param material the value for core.samples.material
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setMaterial(String material);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.habitat
	 *
	 * @return the value of core.samples.habitat
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getHabitat();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.habitat
	 *
	 * @param habitat the value for core.samples.habitat
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setHabitat(String habitat);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.hab_lite
	 *
	 * @return the value of core.samples.hab_lite
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getHabLite();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.hab_lite
	 *
	 * @param habLite the value for core.samples.hab_lite
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setHabLite(String habLite);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.country
	 *
	 * @return the value of core.samples.country
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getCountry();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.country
	 *
	 * @param country the value for core.samples.country
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setCountry(String country);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.project
	 *
	 * @return the value of core.samples.project
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public Integer getProject();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.project
	 *
	 * @param project the value for core.samples.project
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setProject(Integer project);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.own
	 *
	 * @return the value of core.samples.own
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getOwn();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.own
	 *
	 * @param own the value for core.samples.own
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setOwn(String own);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.pool
	 *
	 * @return the value of core.samples.pool
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public Short getPool();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.pool
	 *
	 * @param pool the value for core.samples.pool
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setPool(Short pool);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.id
	 *
	 * @return the value of core.samples.id
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public Integer getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.id
	 *
	 * @param id the value for core.samples.id
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setId(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.geom
	 *
	 * @return the value of core.samples.geom
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public Object getGeom();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.geom
	 *
	 * @param geom the value for core.samples.geom
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setGeom(Object geom);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.device
	 *
	 * @return the value of core.samples.device
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getDevice();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.device
	 *
	 * @param device the value for core.samples.device
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setDevice(String device);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.biome
	 *
	 * @return the value of core.samples.biome
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getBiome();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.biome
	 *
	 * @param biome the value for core.samples.biome
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setBiome(String biome);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column core.samples.feature
	 *
	 * @return the value of core.samples.feature
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public String getFeature();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column core.samples.feature
	 *
	 * @param feature the value for core.samples.feature
	 *
	 * @mbggenerated Sun Jun 17 00:41:33 CEST 2012
	 */
	public void setFeature(String feature);

}