package net.megx.megdb.beans;

import net.megx.model.Article;

public class Metagenome extends Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.sid
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.geom
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private Object geom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.site_name
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.lat
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String lat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.lon
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String lon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.latlon
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String latlon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.depth
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String depth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.date_taken
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String dateTaken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.hab_lite
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String habLite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.hab_uri
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String habUri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.study_type
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String studyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.entity_name
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String entityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.entity_url
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String entityUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.entity_country
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String entityCountry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.entity_iho
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String entityIho;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.entity_region
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String entityRegion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.entity_descr
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String entityDescr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.temperature
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String temperature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.salinity
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String salinity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.oxygen
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String oxygen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_r8.metagenomes.chlorophyll
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	private String chlorophyll;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.sid
	 * @return  the value of web_r8.metagenomes.sid
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.sid
	 * @param sid  the value for web_r8.metagenomes.sid
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.geom
	 * @return  the value of web_r8.metagenomes.geom
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public Object getGeom() {
		return geom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.geom
	 * @param geom  the value for web_r8.metagenomes.geom
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setGeom(Object geom) {
		this.geom = geom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.site_name
	 * @return  the value of web_r8.metagenomes.site_name
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.site_name
	 * @param siteName  the value for web_r8.metagenomes.site_name
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.lat
	 * @return  the value of web_r8.metagenomes.lat
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getLat() {
		return lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.lat
	 * @param lat  the value for web_r8.metagenomes.lat
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setLat(String lat) {
		this.lat = lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.lon
	 * @return  the value of web_r8.metagenomes.lon
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getLon() {
		return lon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.lon
	 * @param lon  the value for web_r8.metagenomes.lon
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setLon(String lon) {
		this.lon = lon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.latlon
	 * @return  the value of web_r8.metagenomes.latlon
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getLatlon() {
		return latlon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.latlon
	 * @param latlon  the value for web_r8.metagenomes.latlon
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setLatlon(String latlon) {
		this.latlon = latlon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.depth
	 * @return  the value of web_r8.metagenomes.depth
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getDepth() {
		return depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.depth
	 * @param depth  the value for web_r8.metagenomes.depth
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setDepth(String depth) {
		this.depth = depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.date_taken
	 * @return  the value of web_r8.metagenomes.date_taken
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getDateTaken() {
		return dateTaken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.date_taken
	 * @param dateTaken  the value for web_r8.metagenomes.date_taken
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setDateTaken(String dateTaken) {
		this.dateTaken = dateTaken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.hab_lite
	 * @return  the value of web_r8.metagenomes.hab_lite
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getHabLite() {
		return habLite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.hab_lite
	 * @param habLite  the value for web_r8.metagenomes.hab_lite
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setHabLite(String habLite) {
		this.habLite = habLite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.hab_uri
	 * @return  the value of web_r8.metagenomes.hab_uri
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getHabUri() {
		return habUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.hab_uri
	 * @param habUri  the value for web_r8.metagenomes.hab_uri
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setHabUri(String habUri) {
		this.habUri = habUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.study_type
	 * @return  the value of web_r8.metagenomes.study_type
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getStudyType() {
		return studyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.study_type
	 * @param studyType  the value for web_r8.metagenomes.study_type
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setStudyType(String studyType) {
		this.studyType = studyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.entity_name
	 * @return  the value of web_r8.metagenomes.entity_name
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getEntityName() {
		return entityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.entity_name
	 * @param entityName  the value for web_r8.metagenomes.entity_name
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.entity_url
	 * @return  the value of web_r8.metagenomes.entity_url
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getEntityUrl() {
		return entityUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.entity_url
	 * @param entityUrl  the value for web_r8.metagenomes.entity_url
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setEntityUrl(String entityUrl) {
		this.entityUrl = entityUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.entity_country
	 * @return  the value of web_r8.metagenomes.entity_country
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getEntityCountry() {
		return entityCountry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.entity_country
	 * @param entityCountry  the value for web_r8.metagenomes.entity_country
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setEntityCountry(String entityCountry) {
		this.entityCountry = entityCountry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.entity_iho
	 * @return  the value of web_r8.metagenomes.entity_iho
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getEntityIho() {
		return entityIho;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.entity_iho
	 * @param entityIho  the value for web_r8.metagenomes.entity_iho
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setEntityIho(String entityIho) {
		this.entityIho = entityIho;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.entity_region
	 * @return  the value of web_r8.metagenomes.entity_region
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getEntityRegion() {
		return entityRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.entity_region
	 * @param entityRegion  the value for web_r8.metagenomes.entity_region
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setEntityRegion(String entityRegion) {
		this.entityRegion = entityRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.entity_descr
	 * @return  the value of web_r8.metagenomes.entity_descr
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getEntityDescr() {
		return entityDescr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.entity_descr
	 * @param entityDescr  the value for web_r8.metagenomes.entity_descr
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setEntityDescr(String entityDescr) {
		this.entityDescr = entityDescr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.temperature
	 * @return  the value of web_r8.metagenomes.temperature
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getTemperature() {
		return temperature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.temperature
	 * @param temperature  the value for web_r8.metagenomes.temperature
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.salinity
	 * @return  the value of web_r8.metagenomes.salinity
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getSalinity() {
		return salinity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.salinity
	 * @param salinity  the value for web_r8.metagenomes.salinity
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setSalinity(String salinity) {
		this.salinity = salinity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.oxygen
	 * @return  the value of web_r8.metagenomes.oxygen
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getOxygen() {
		return oxygen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.oxygen
	 * @param oxygen  the value for web_r8.metagenomes.oxygen
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setOxygen(String oxygen) {
		this.oxygen = oxygen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_r8.metagenomes.chlorophyll
	 * @return  the value of web_r8.metagenomes.chlorophyll
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getChlorophyll() {
		return chlorophyll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_r8.metagenomes.chlorophyll
	 * @param chlorophyll  the value for web_r8.metagenomes.chlorophyll
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setChlorophyll(String chlorophyll) {
		this.chlorophyll = chlorophyll;
	}

	void hallo(){};
}