package net.megx.megdb.beans;

import java.util.ArrayList;
import java.util.List;

public class MetagenomeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public MetagenomeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSidIsNull() {
			addCriterion("sid is null");
			return (Criteria) this;
		}

		public Criteria andSidIsNotNull() {
			addCriterion("sid is not null");
			return (Criteria) this;
		}

		public Criteria andSidEqualTo(Integer value) {
			addCriterion("sid =", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidNotEqualTo(Integer value) {
			addCriterion("sid <>", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidGreaterThan(Integer value) {
			addCriterion("sid >", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidGreaterThanOrEqualTo(Integer value) {
			addCriterion("sid >=", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidLessThan(Integer value) {
			addCriterion("sid <", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidLessThanOrEqualTo(Integer value) {
			addCriterion("sid <=", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidIn(List<Integer> values) {
			addCriterion("sid in", values, "sid");
			return (Criteria) this;
		}

		public Criteria andSidNotIn(List<Integer> values) {
			addCriterion("sid not in", values, "sid");
			return (Criteria) this;
		}

		public Criteria andSidBetween(Integer value1, Integer value2) {
			addCriterion("sid between", value1, value2, "sid");
			return (Criteria) this;
		}

		public Criteria andSidNotBetween(Integer value1, Integer value2) {
			addCriterion("sid not between", value1, value2, "sid");
			return (Criteria) this;
		}

		public Criteria andGeomIsNull() {
			addCriterion("geom is null");
			return (Criteria) this;
		}

		public Criteria andGeomIsNotNull() {
			addCriterion("geom is not null");
			return (Criteria) this;
		}

		public Criteria andGeomEqualTo(Object value) {
			addCriterion("geom =", value, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomNotEqualTo(Object value) {
			addCriterion("geom <>", value, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomGreaterThan(Object value) {
			addCriterion("geom >", value, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomGreaterThanOrEqualTo(Object value) {
			addCriterion("geom >=", value, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomLessThan(Object value) {
			addCriterion("geom <", value, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomLessThanOrEqualTo(Object value) {
			addCriterion("geom <=", value, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomIn(List<Object> values) {
			addCriterion("geom in", values, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomNotIn(List<Object> values) {
			addCriterion("geom not in", values, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomBetween(Object value1, Object value2) {
			addCriterion("geom between", value1, value2, "geom");
			return (Criteria) this;
		}

		public Criteria andGeomNotBetween(Object value1, Object value2) {
			addCriterion("geom not between", value1, value2, "geom");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNull() {
			addCriterion("site_name is null");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNotNull() {
			addCriterion("site_name is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNameEqualTo(String value) {
			addCriterion("site_name =", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotEqualTo(String value) {
			addCriterion("site_name <>", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThan(String value) {
			addCriterion("site_name >", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
			addCriterion("site_name >=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThan(String value) {
			addCriterion("site_name <", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThanOrEqualTo(String value) {
			addCriterion("site_name <=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLike(String value) {
			addCriterion("site_name like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotLike(String value) {
			addCriterion("site_name not like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameIn(List<String> values) {
			addCriterion("site_name in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotIn(List<String> values) {
			addCriterion("site_name not in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameBetween(String value1, String value2) {
			addCriterion("site_name between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotBetween(String value1, String value2) {
			addCriterion("site_name not between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andLatIsNull() {
			addCriterion("lat is null");
			return (Criteria) this;
		}

		public Criteria andLatIsNotNull() {
			addCriterion("lat is not null");
			return (Criteria) this;
		}

		public Criteria andLatEqualTo(String value) {
			addCriterion("lat =", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatNotEqualTo(String value) {
			addCriterion("lat <>", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatGreaterThan(String value) {
			addCriterion("lat >", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatGreaterThanOrEqualTo(String value) {
			addCriterion("lat >=", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatLessThan(String value) {
			addCriterion("lat <", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatLessThanOrEqualTo(String value) {
			addCriterion("lat <=", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatLike(String value) {
			addCriterion("lat like", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatNotLike(String value) {
			addCriterion("lat not like", value, "lat");
			return (Criteria) this;
		}

		public Criteria andLatIn(List<String> values) {
			addCriterion("lat in", values, "lat");
			return (Criteria) this;
		}

		public Criteria andLatNotIn(List<String> values) {
			addCriterion("lat not in", values, "lat");
			return (Criteria) this;
		}

		public Criteria andLatBetween(String value1, String value2) {
			addCriterion("lat between", value1, value2, "lat");
			return (Criteria) this;
		}

		public Criteria andLatNotBetween(String value1, String value2) {
			addCriterion("lat not between", value1, value2, "lat");
			return (Criteria) this;
		}

		public Criteria andLonIsNull() {
			addCriterion("lon is null");
			return (Criteria) this;
		}

		public Criteria andLonIsNotNull() {
			addCriterion("lon is not null");
			return (Criteria) this;
		}

		public Criteria andLonEqualTo(String value) {
			addCriterion("lon =", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonNotEqualTo(String value) {
			addCriterion("lon <>", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonGreaterThan(String value) {
			addCriterion("lon >", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonGreaterThanOrEqualTo(String value) {
			addCriterion("lon >=", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonLessThan(String value) {
			addCriterion("lon <", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonLessThanOrEqualTo(String value) {
			addCriterion("lon <=", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonLike(String value) {
			addCriterion("lon like", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonNotLike(String value) {
			addCriterion("lon not like", value, "lon");
			return (Criteria) this;
		}

		public Criteria andLonIn(List<String> values) {
			addCriterion("lon in", values, "lon");
			return (Criteria) this;
		}

		public Criteria andLonNotIn(List<String> values) {
			addCriterion("lon not in", values, "lon");
			return (Criteria) this;
		}

		public Criteria andLonBetween(String value1, String value2) {
			addCriterion("lon between", value1, value2, "lon");
			return (Criteria) this;
		}

		public Criteria andLonNotBetween(String value1, String value2) {
			addCriterion("lon not between", value1, value2, "lon");
			return (Criteria) this;
		}

		public Criteria andLatlonIsNull() {
			addCriterion("latlon is null");
			return (Criteria) this;
		}

		public Criteria andLatlonIsNotNull() {
			addCriterion("latlon is not null");
			return (Criteria) this;
		}

		public Criteria andLatlonEqualTo(String value) {
			addCriterion("latlon =", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonNotEqualTo(String value) {
			addCriterion("latlon <>", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonGreaterThan(String value) {
			addCriterion("latlon >", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonGreaterThanOrEqualTo(String value) {
			addCriterion("latlon >=", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonLessThan(String value) {
			addCriterion("latlon <", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonLessThanOrEqualTo(String value) {
			addCriterion("latlon <=", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonLike(String value) {
			addCriterion("latlon like", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonNotLike(String value) {
			addCriterion("latlon not like", value, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonIn(List<String> values) {
			addCriterion("latlon in", values, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonNotIn(List<String> values) {
			addCriterion("latlon not in", values, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonBetween(String value1, String value2) {
			addCriterion("latlon between", value1, value2, "latlon");
			return (Criteria) this;
		}

		public Criteria andLatlonNotBetween(String value1, String value2) {
			addCriterion("latlon not between", value1, value2, "latlon");
			return (Criteria) this;
		}

		public Criteria andDepthIsNull() {
			addCriterion("depth is null");
			return (Criteria) this;
		}

		public Criteria andDepthIsNotNull() {
			addCriterion("depth is not null");
			return (Criteria) this;
		}

		public Criteria andDepthEqualTo(String value) {
			addCriterion("depth =", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotEqualTo(String value) {
			addCriterion("depth <>", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthGreaterThan(String value) {
			addCriterion("depth >", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthGreaterThanOrEqualTo(String value) {
			addCriterion("depth >=", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthLessThan(String value) {
			addCriterion("depth <", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthLessThanOrEqualTo(String value) {
			addCriterion("depth <=", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthLike(String value) {
			addCriterion("depth like", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotLike(String value) {
			addCriterion("depth not like", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthIn(List<String> values) {
			addCriterion("depth in", values, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotIn(List<String> values) {
			addCriterion("depth not in", values, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthBetween(String value1, String value2) {
			addCriterion("depth between", value1, value2, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotBetween(String value1, String value2) {
			addCriterion("depth not between", value1, value2, "depth");
			return (Criteria) this;
		}

		public Criteria andDateTakenIsNull() {
			addCriterion("date_taken is null");
			return (Criteria) this;
		}

		public Criteria andDateTakenIsNotNull() {
			addCriterion("date_taken is not null");
			return (Criteria) this;
		}

		public Criteria andDateTakenEqualTo(String value) {
			addCriterion("date_taken =", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenNotEqualTo(String value) {
			addCriterion("date_taken <>", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenGreaterThan(String value) {
			addCriterion("date_taken >", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenGreaterThanOrEqualTo(String value) {
			addCriterion("date_taken >=", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenLessThan(String value) {
			addCriterion("date_taken <", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenLessThanOrEqualTo(String value) {
			addCriterion("date_taken <=", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenLike(String value) {
			addCriterion("date_taken like", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenNotLike(String value) {
			addCriterion("date_taken not like", value, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenIn(List<String> values) {
			addCriterion("date_taken in", values, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenNotIn(List<String> values) {
			addCriterion("date_taken not in", values, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenBetween(String value1, String value2) {
			addCriterion("date_taken between", value1, value2, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andDateTakenNotBetween(String value1, String value2) {
			addCriterion("date_taken not between", value1, value2, "dateTaken");
			return (Criteria) this;
		}

		public Criteria andHabLiteIsNull() {
			addCriterion("hab_lite is null");
			return (Criteria) this;
		}

		public Criteria andHabLiteIsNotNull() {
			addCriterion("hab_lite is not null");
			return (Criteria) this;
		}

		public Criteria andHabLiteEqualTo(String value) {
			addCriterion("hab_lite =", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteNotEqualTo(String value) {
			addCriterion("hab_lite <>", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteGreaterThan(String value) {
			addCriterion("hab_lite >", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteGreaterThanOrEqualTo(String value) {
			addCriterion("hab_lite >=", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteLessThan(String value) {
			addCriterion("hab_lite <", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteLessThanOrEqualTo(String value) {
			addCriterion("hab_lite <=", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteLike(String value) {
			addCriterion("hab_lite like", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteNotLike(String value) {
			addCriterion("hab_lite not like", value, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteIn(List<String> values) {
			addCriterion("hab_lite in", values, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteNotIn(List<String> values) {
			addCriterion("hab_lite not in", values, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteBetween(String value1, String value2) {
			addCriterion("hab_lite between", value1, value2, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabLiteNotBetween(String value1, String value2) {
			addCriterion("hab_lite not between", value1, value2, "habLite");
			return (Criteria) this;
		}

		public Criteria andHabUriIsNull() {
			addCriterion("hab_uri is null");
			return (Criteria) this;
		}

		public Criteria andHabUriIsNotNull() {
			addCriterion("hab_uri is not null");
			return (Criteria) this;
		}

		public Criteria andHabUriEqualTo(String value) {
			addCriterion("hab_uri =", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriNotEqualTo(String value) {
			addCriterion("hab_uri <>", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriGreaterThan(String value) {
			addCriterion("hab_uri >", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriGreaterThanOrEqualTo(String value) {
			addCriterion("hab_uri >=", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriLessThan(String value) {
			addCriterion("hab_uri <", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriLessThanOrEqualTo(String value) {
			addCriterion("hab_uri <=", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriLike(String value) {
			addCriterion("hab_uri like", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriNotLike(String value) {
			addCriterion("hab_uri not like", value, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriIn(List<String> values) {
			addCriterion("hab_uri in", values, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriNotIn(List<String> values) {
			addCriterion("hab_uri not in", values, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriBetween(String value1, String value2) {
			addCriterion("hab_uri between", value1, value2, "habUri");
			return (Criteria) this;
		}

		public Criteria andHabUriNotBetween(String value1, String value2) {
			addCriterion("hab_uri not between", value1, value2, "habUri");
			return (Criteria) this;
		}

		public Criteria andStudyTypeIsNull() {
			addCriterion("study_type is null");
			return (Criteria) this;
		}

		public Criteria andStudyTypeIsNotNull() {
			addCriterion("study_type is not null");
			return (Criteria) this;
		}

		public Criteria andStudyTypeEqualTo(String value) {
			addCriterion("study_type =", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeNotEqualTo(String value) {
			addCriterion("study_type <>", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeGreaterThan(String value) {
			addCriterion("study_type >", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeGreaterThanOrEqualTo(String value) {
			addCriterion("study_type >=", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeLessThan(String value) {
			addCriterion("study_type <", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeLessThanOrEqualTo(String value) {
			addCriterion("study_type <=", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeLike(String value) {
			addCriterion("study_type like", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeNotLike(String value) {
			addCriterion("study_type not like", value, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeIn(List<String> values) {
			addCriterion("study_type in", values, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeNotIn(List<String> values) {
			addCriterion("study_type not in", values, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeBetween(String value1, String value2) {
			addCriterion("study_type between", value1, value2, "studyType");
			return (Criteria) this;
		}

		public Criteria andStudyTypeNotBetween(String value1, String value2) {
			addCriterion("study_type not between", value1, value2, "studyType");
			return (Criteria) this;
		}

		public Criteria andEntityNameIsNull() {
			addCriterion("entity_name is null");
			return (Criteria) this;
		}

		public Criteria andEntityNameIsNotNull() {
			addCriterion("entity_name is not null");
			return (Criteria) this;
		}

		public Criteria andEntityNameEqualTo(String value) {
			addCriterion("entity_name =", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameNotEqualTo(String value) {
			addCriterion("entity_name <>", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameGreaterThan(String value) {
			addCriterion("entity_name >", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameGreaterThanOrEqualTo(String value) {
			addCriterion("entity_name >=", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameLessThan(String value) {
			addCriterion("entity_name <", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameLessThanOrEqualTo(String value) {
			addCriterion("entity_name <=", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameLike(String value) {
			addCriterion("entity_name like", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameNotLike(String value) {
			addCriterion("entity_name not like", value, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameIn(List<String> values) {
			addCriterion("entity_name in", values, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameNotIn(List<String> values) {
			addCriterion("entity_name not in", values, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameBetween(String value1, String value2) {
			addCriterion("entity_name between", value1, value2, "entityName");
			return (Criteria) this;
		}

		public Criteria andEntityNameNotBetween(String value1, String value2) {
			addCriterion("entity_name not between", value1, value2,
					"entityName");
			return (Criteria) this;
		}

		public Criteria andEntityUrlIsNull() {
			addCriterion("entity_url is null");
			return (Criteria) this;
		}

		public Criteria andEntityUrlIsNotNull() {
			addCriterion("entity_url is not null");
			return (Criteria) this;
		}

		public Criteria andEntityUrlEqualTo(String value) {
			addCriterion("entity_url =", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlNotEqualTo(String value) {
			addCriterion("entity_url <>", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlGreaterThan(String value) {
			addCriterion("entity_url >", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlGreaterThanOrEqualTo(String value) {
			addCriterion("entity_url >=", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlLessThan(String value) {
			addCriterion("entity_url <", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlLessThanOrEqualTo(String value) {
			addCriterion("entity_url <=", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlLike(String value) {
			addCriterion("entity_url like", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlNotLike(String value) {
			addCriterion("entity_url not like", value, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlIn(List<String> values) {
			addCriterion("entity_url in", values, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlNotIn(List<String> values) {
			addCriterion("entity_url not in", values, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlBetween(String value1, String value2) {
			addCriterion("entity_url between", value1, value2, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityUrlNotBetween(String value1, String value2) {
			addCriterion("entity_url not between", value1, value2, "entityUrl");
			return (Criteria) this;
		}

		public Criteria andEntityCountryIsNull() {
			addCriterion("entity_country is null");
			return (Criteria) this;
		}

		public Criteria andEntityCountryIsNotNull() {
			addCriterion("entity_country is not null");
			return (Criteria) this;
		}

		public Criteria andEntityCountryEqualTo(String value) {
			addCriterion("entity_country =", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryNotEqualTo(String value) {
			addCriterion("entity_country <>", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryGreaterThan(String value) {
			addCriterion("entity_country >", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryGreaterThanOrEqualTo(String value) {
			addCriterion("entity_country >=", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryLessThan(String value) {
			addCriterion("entity_country <", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryLessThanOrEqualTo(String value) {
			addCriterion("entity_country <=", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryLike(String value) {
			addCriterion("entity_country like", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryNotLike(String value) {
			addCriterion("entity_country not like", value, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryIn(List<String> values) {
			addCriterion("entity_country in", values, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryNotIn(List<String> values) {
			addCriterion("entity_country not in", values, "entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryBetween(String value1, String value2) {
			addCriterion("entity_country between", value1, value2,
					"entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityCountryNotBetween(String value1, String value2) {
			addCriterion("entity_country not between", value1, value2,
					"entityCountry");
			return (Criteria) this;
		}

		public Criteria andEntityIhoIsNull() {
			addCriterion("entity_iho is null");
			return (Criteria) this;
		}

		public Criteria andEntityIhoIsNotNull() {
			addCriterion("entity_iho is not null");
			return (Criteria) this;
		}

		public Criteria andEntityIhoEqualTo(String value) {
			addCriterion("entity_iho =", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoNotEqualTo(String value) {
			addCriterion("entity_iho <>", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoGreaterThan(String value) {
			addCriterion("entity_iho >", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoGreaterThanOrEqualTo(String value) {
			addCriterion("entity_iho >=", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoLessThan(String value) {
			addCriterion("entity_iho <", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoLessThanOrEqualTo(String value) {
			addCriterion("entity_iho <=", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoLike(String value) {
			addCriterion("entity_iho like", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoNotLike(String value) {
			addCriterion("entity_iho not like", value, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoIn(List<String> values) {
			addCriterion("entity_iho in", values, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoNotIn(List<String> values) {
			addCriterion("entity_iho not in", values, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoBetween(String value1, String value2) {
			addCriterion("entity_iho between", value1, value2, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityIhoNotBetween(String value1, String value2) {
			addCriterion("entity_iho not between", value1, value2, "entityIho");
			return (Criteria) this;
		}

		public Criteria andEntityRegionIsNull() {
			addCriterion("entity_region is null");
			return (Criteria) this;
		}

		public Criteria andEntityRegionIsNotNull() {
			addCriterion("entity_region is not null");
			return (Criteria) this;
		}

		public Criteria andEntityRegionEqualTo(String value) {
			addCriterion("entity_region =", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionNotEqualTo(String value) {
			addCriterion("entity_region <>", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionGreaterThan(String value) {
			addCriterion("entity_region >", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionGreaterThanOrEqualTo(String value) {
			addCriterion("entity_region >=", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionLessThan(String value) {
			addCriterion("entity_region <", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionLessThanOrEqualTo(String value) {
			addCriterion("entity_region <=", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionLike(String value) {
			addCriterion("entity_region like", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionNotLike(String value) {
			addCriterion("entity_region not like", value, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionIn(List<String> values) {
			addCriterion("entity_region in", values, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionNotIn(List<String> values) {
			addCriterion("entity_region not in", values, "entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionBetween(String value1, String value2) {
			addCriterion("entity_region between", value1, value2,
					"entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityRegionNotBetween(String value1, String value2) {
			addCriterion("entity_region not between", value1, value2,
					"entityRegion");
			return (Criteria) this;
		}

		public Criteria andEntityDescrIsNull() {
			addCriterion("entity_descr is null");
			return (Criteria) this;
		}

		public Criteria andEntityDescrIsNotNull() {
			addCriterion("entity_descr is not null");
			return (Criteria) this;
		}

		public Criteria andEntityDescrEqualTo(String value) {
			addCriterion("entity_descr =", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrNotEqualTo(String value) {
			addCriterion("entity_descr <>", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrGreaterThan(String value) {
			addCriterion("entity_descr >", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrGreaterThanOrEqualTo(String value) {
			addCriterion("entity_descr >=", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrLessThan(String value) {
			addCriterion("entity_descr <", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrLessThanOrEqualTo(String value) {
			addCriterion("entity_descr <=", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrLike(String value) {
			addCriterion("entity_descr like", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrNotLike(String value) {
			addCriterion("entity_descr not like", value, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrIn(List<String> values) {
			addCriterion("entity_descr in", values, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrNotIn(List<String> values) {
			addCriterion("entity_descr not in", values, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrBetween(String value1, String value2) {
			addCriterion("entity_descr between", value1, value2, "entityDescr");
			return (Criteria) this;
		}

		public Criteria andEntityDescrNotBetween(String value1, String value2) {
			addCriterion("entity_descr not between", value1, value2,
					"entityDescr");
			return (Criteria) this;
		}

		public Criteria andTemperatureIsNull() {
			addCriterion("temperature is null");
			return (Criteria) this;
		}

		public Criteria andTemperatureIsNotNull() {
			addCriterion("temperature is not null");
			return (Criteria) this;
		}

		public Criteria andTemperatureEqualTo(String value) {
			addCriterion("temperature =", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotEqualTo(String value) {
			addCriterion("temperature <>", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureGreaterThan(String value) {
			addCriterion("temperature >", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureGreaterThanOrEqualTo(String value) {
			addCriterion("temperature >=", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureLessThan(String value) {
			addCriterion("temperature <", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureLessThanOrEqualTo(String value) {
			addCriterion("temperature <=", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureLike(String value) {
			addCriterion("temperature like", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotLike(String value) {
			addCriterion("temperature not like", value, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureIn(List<String> values) {
			addCriterion("temperature in", values, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotIn(List<String> values) {
			addCriterion("temperature not in", values, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureBetween(String value1, String value2) {
			addCriterion("temperature between", value1, value2, "temperature");
			return (Criteria) this;
		}

		public Criteria andTemperatureNotBetween(String value1, String value2) {
			addCriterion("temperature not between", value1, value2,
					"temperature");
			return (Criteria) this;
		}

		public Criteria andSalinityIsNull() {
			addCriterion("salinity is null");
			return (Criteria) this;
		}

		public Criteria andSalinityIsNotNull() {
			addCriterion("salinity is not null");
			return (Criteria) this;
		}

		public Criteria andSalinityEqualTo(String value) {
			addCriterion("salinity =", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityNotEqualTo(String value) {
			addCriterion("salinity <>", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityGreaterThan(String value) {
			addCriterion("salinity >", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityGreaterThanOrEqualTo(String value) {
			addCriterion("salinity >=", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityLessThan(String value) {
			addCriterion("salinity <", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityLessThanOrEqualTo(String value) {
			addCriterion("salinity <=", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityLike(String value) {
			addCriterion("salinity like", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityNotLike(String value) {
			addCriterion("salinity not like", value, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityIn(List<String> values) {
			addCriterion("salinity in", values, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityNotIn(List<String> values) {
			addCriterion("salinity not in", values, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityBetween(String value1, String value2) {
			addCriterion("salinity between", value1, value2, "salinity");
			return (Criteria) this;
		}

		public Criteria andSalinityNotBetween(String value1, String value2) {
			addCriterion("salinity not between", value1, value2, "salinity");
			return (Criteria) this;
		}

		public Criteria andOxygenIsNull() {
			addCriterion("oxygen is null");
			return (Criteria) this;
		}

		public Criteria andOxygenIsNotNull() {
			addCriterion("oxygen is not null");
			return (Criteria) this;
		}

		public Criteria andOxygenEqualTo(String value) {
			addCriterion("oxygen =", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenNotEqualTo(String value) {
			addCriterion("oxygen <>", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenGreaterThan(String value) {
			addCriterion("oxygen >", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenGreaterThanOrEqualTo(String value) {
			addCriterion("oxygen >=", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenLessThan(String value) {
			addCriterion("oxygen <", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenLessThanOrEqualTo(String value) {
			addCriterion("oxygen <=", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenLike(String value) {
			addCriterion("oxygen like", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenNotLike(String value) {
			addCriterion("oxygen not like", value, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenIn(List<String> values) {
			addCriterion("oxygen in", values, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenNotIn(List<String> values) {
			addCriterion("oxygen not in", values, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenBetween(String value1, String value2) {
			addCriterion("oxygen between", value1, value2, "oxygen");
			return (Criteria) this;
		}

		public Criteria andOxygenNotBetween(String value1, String value2) {
			addCriterion("oxygen not between", value1, value2, "oxygen");
			return (Criteria) this;
		}

		public Criteria andChlorophyllIsNull() {
			addCriterion("chlorophyll is null");
			return (Criteria) this;
		}

		public Criteria andChlorophyllIsNotNull() {
			addCriterion("chlorophyll is not null");
			return (Criteria) this;
		}

		public Criteria andChlorophyllEqualTo(String value) {
			addCriterion("chlorophyll =", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllNotEqualTo(String value) {
			addCriterion("chlorophyll <>", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllGreaterThan(String value) {
			addCriterion("chlorophyll >", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllGreaterThanOrEqualTo(String value) {
			addCriterion("chlorophyll >=", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllLessThan(String value) {
			addCriterion("chlorophyll <", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllLessThanOrEqualTo(String value) {
			addCriterion("chlorophyll <=", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllLike(String value) {
			addCriterion("chlorophyll like", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllNotLike(String value) {
			addCriterion("chlorophyll not like", value, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllIn(List<String> values) {
			addCriterion("chlorophyll in", values, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllNotIn(List<String> values) {
			addCriterion("chlorophyll not in", values, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllBetween(String value1, String value2) {
			addCriterion("chlorophyll between", value1, value2, "chlorophyll");
			return (Criteria) this;
		}

		public Criteria andChlorophyllNotBetween(String value1, String value2) {
			addCriterion("chlorophyll not between", value1, value2,
					"chlorophyll");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:02:44 CEST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_r8.metagenomes
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 13 05:34:00 CEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}