package net.megx.megdb.services;

import net.megx.megdb.beans.Article;
import net.megx.megdb.beans.ArticleExample;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int deleteByPrimaryKey(@Param("id") String id, @Param("idCode") String idCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    Article selectByPrimaryKey(@Param("id") String id, @Param("idCode") String idCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.articles
     *
     * @mbggenerated Wed Jun 13 06:09:31 CEST 2012
     */
    int updateByPrimaryKey(Article record);
}