package net.megx.megdb.services;

import net.megx.megdb.beans.Metagenome;
import net.megx.megdb.beans.MetagenomeExample;
import org.apache.ibatis.annotations.Param;

public interface MetagenomeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:09:31 CEST 2012
	 */
	int countByExample(MetagenomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:09:31 CEST 2012
	 */
	int insert(Metagenome record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:09:31 CEST 2012
	 */
	int insertSelective(Metagenome record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:09:31 CEST 2012
	 */
	int updateByExampleSelective(@Param("record") Metagenome record,
			@Param("example") MetagenomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_r8.metagenomes
	 * @mbggenerated  Wed Jun 13 06:09:31 CEST 2012
	 */
	int updateByExample(@Param("record") Metagenome record,
			@Param("example") MetagenomeExample example);

	int testins();
}